### PR TITLE
Swift 4 compatible

### PR DESCRIPTION
**Pull request by basvankuijck**

### CODE REVIEW

**Comment by nakiostudio** [comment]
Hi @basvankuijck 👋 

Thanks for looking after another Swift migration! @muukii was a bit faster this time with his PR #61. 

I would like to wait for Xcode 9 release before updating the `.swift-version` file. Would you like to only change that file in this PR to have everything ready for the Xcode release?

**Comment by ghost** [comment]
cool

**Comment by nakiostudio** [comment]
It's the moment @basvankuijck :)

**Review by nakiostudio — APPROVED** [review]

**Comment by muukii** [comment]
here we go!

**Comment by muukii** [comment]
@basvankuijck 
Please change `SWIFT_VERSION`to Swift4.0 in the xcconfig?
I think we need it when building with Carthage.

**Comment by nakiostudio** [comment]
Thank you @basvankuijck 🙌 

I will create a release and fix the issue with Danger :)

**Comment by muukii** [comment]
@basvankuijck Thank you!

**Pull request merged**
