### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by basvankuijck**

### CODE REVIEW

**Comment by nakiostudio** [comment]
Hi @basvankuijck 👋 

Thank you for this, amazing effort! You even updated the image with the code snippet, no words 💯 

However, it's still too soon to merge on master a Swift 3.0 implementation of the library. I was thinking on creating a swift-3.0 branch and merge your PR into it, then let the users interested know with a note in the README file. What do you think?

Thank you once again 👍

**Comment by basvankuijck** [comment]
No problem. We really love your DSL and we can't do without a swift3 version. 
Most of the work was done by xcode's auto conversion. Any remaining warnings and errors I fixed manually, but it was no effort. I still see there are some wrong replacements in docblocks and comments.
A swift-3 branch would be awesome.

Thanks for your work!

**Comment by basvankuijck** [comment]
Also travis seems to be missing a `DANGER_GITHUB_API_TOKEN` environment variable for travis to pass: https://travis-ci.org/nakiostudio/EasyPeasy/builds/153531592

**Comment by nakiostudio** [comment]
I've seen it. Ignore the error building, the tests are passing therefore all good 👍

**Comment by nakiostudio** [comment]
Just published a `swift-3` branch and updated the base branch of your PR, I will merge as soon as Travis finishes 👍

**Pull request merged**
