### PR TITLE
Compatibility with tvOS and OS X

### PR DESCRIPTION
**Pull request by nakiostudio**
This PR adds compatibility with tvOS and OSX, also includes a new OS X demo project:

demo_macos

### CODE REVIEW

**Comment by nakiostudio** [comment]
## Current coverage for Demo macOS.app is `95%`
Files changed | - | - 
--- | --- | ---
NSImage+Easy.swift | `83%` | ✅
SideBarView.swift | `90%` | ✅
FeedView.swift | `94%` | ✅
TweetView.swift | `96%` | ✅
TweetModel.swift | `100%` | ✅
FeedController.swift | `100%` | ✅
AppDelegate.swift | `100%` | ✅
NSColor+Easy.swift | `100%` | ✅

---
## Current coverage for EasyPeasy.framework is `99%`
Files changed | - | - 
--- | --- | ---
ReferenceAttribute+AppKit.swift | `92%` | ✅
Attribute+Install.swift | `98%` | ✅
Attribute.swift | `100%` | ✅
CompoundAttribute.swift | `100%` | ✅
Constant.swift | `100%` | ✅
DimensionAttribute+AppKit.swift | `100%` | ✅
DimensionAttribute.swift | `100%` | ✅
Item.swift | `100%` | ✅
NSLayoutConstraint+Internal.swift | `100%` | ✅
NSView+Easy.swift | `100%` | ✅
PositionAttribute+AppKit.swift | `100%` | ✅
PositionAttribute.swift | `100%` | ✅
Item+AppKit.swift | `100%` | ✅

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

## Current coverage for EasyPeasy.framework is `99%`
Files changed | - | - 
--- | --- | ---
ReferenceAttribute+AppKit.swift | `92%` | ✅
Attribute+Install.swift | `98%` | ✅
Attribute.swift | `100%` | ✅
CompoundAttribute.swift | `100%` | ✅
Constant.swift | `100%` | ✅
DimensionAttribute+AppKit.swift | `100%` | ✅
DimensionAttribute.swift | `100%` | ✅
Item.swift | `100%` | ✅
NSLayoutConstraint+Internal.swift | `100%` | ✅
NSView+Easy.swift | `100%` | ✅
PositionAttribute+AppKit.swift | `100%` | ✅
PositionAttribute.swift | `100%` | ✅
Item+AppKit.swift | `100%` | ✅

---

> Powered by [xcov](https://github.com/nakiostudio/xcov)

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by orta** [comment]
aye

**Comment by r-a-o** [comment]
Tried the Demo macOS app, the Feed View doesn't scroll.

**Comment by nakiostudio** [comment]
It does work to me, which OS X version are you running the app on?

**Comment by r-a-o** [comment]
Great PR 👍

**Comment by r-a-o** [comment]
Am running El Capitan 10.11.4

**Comment by nakiostudio** [comment]
Interesting, I've run it in two different computers, both with El Capitan, and everything worked fine.

**Comment by r-a-o** [comment]
Oops my bad, I was trying to drag the view instead of scrolling

**Comment by r-a-o** [comment]
How do I make the scroll bar visible in this?

**Comment by nakiostudio** [comment]
Hey @r-a-o 👋 
Please consider that the demo project is purely a demo of EasyPeasy running on OS X, for questions not related with the project please use the usual channels. Thanks!

**Comment by r-a-o** [comment]
Sure, thanks!

**Pull request merged**
